name: app_engine

services:
  php:
    image: alonzoturner/lamp-stack:latest
    container_name: app_engine_php_apache
    environment:
      VIRTUAL_DIR: public
      VIRTUAL_HOST: app-engine.subtext
      VIRTUAL_ADMIN: alonzo.turner@subtext.productions
      PHP_IDE_CONFIG: serverName=AppEngine
      APP_CONFIG: unit.php
    volumes:
    - ./:/var/www
    ports:
    - 80:80
