version: '3.7'

services:
  php:
    image: alonzoturner/lamp-stack:framework
    container_name: php-factory
    environment:
      VIRTUAL_DIR: public
      VIRTUAL_HOST: app-engine.subtext
      VIRTUAL_ADMIN: alonzo.turner@subtextproductions.com
      PHP_IDE_CONFIG: serverName=AppEngine
      APP_CONFIG: unit.php
    volumes:
    - ./:/var/www
    ports:
    - 80:80
    - 443:443
